// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A hint generation AI agent for trivia questions.
 *
 * - generateHint - A function that generates a hint for a given trivia question and answer.
 * - GenerateHintInput - The input type for the generateHint function.
 * - GenerateHintOutput - The return type for the generateHint function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateHintInputSchema = z.object({
  question: z.string().describe('The trivia question to generate a hint for.'),
  answer: z.string().describe('The correct answer to the trivia question.'),
});

export type GenerateHintInput = z.infer<typeof GenerateHintInputSchema>;

const GenerateHintOutputSchema = z.object({
  hint: z.string().describe('A subtle hint related to the trivia question.'),
});

export type GenerateHintOutput = z.infer<typeof GenerateHintOutputSchema>;

export async function generateHint(input: GenerateHintInput): Promise<GenerateHintOutput> {
  return generateHintFlow(input);
}

const generateHintPrompt = ai.definePrompt({
  name: 'generateHintPrompt',
  input: {schema: GenerateHintInputSchema},
  output: {schema: GenerateHintOutputSchema},
  prompt: `You are a helpful game master providing subtle hints to players answering trivia questions.

  Generate a hint for the following trivia question, without giving away the answer directly. The hint should be related to the correct answer and advance the central storyline.

  Question: {{{question}}}
  Answer: {{{answer}}}

  Hint:`,
});

const generateHintFlow = ai.defineFlow(
  {
    name: 'generateHintFlow',
    inputSchema: GenerateHintInputSchema,
    outputSchema: GenerateHintOutputSchema,
  },
  async input => {
    const {output} = await generateHintPrompt(input);
    return output!;
  }
);
